version: '3'

volumes:
  php-api-database:
    external: true

networks:
  php-api-network:
    external: true

services:
  php-api:
    image: ambientum/php:7.3-nginx
    container_name: php-api
    volumes:
      - .:/var/www/app
    ports:
      - "8000:8080"
    networks:
      - php-api-network

  php-api-database:
    image: mysql:5.7
    volumes:
      - php-api-database:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - "MYSQL_DATABASE=database"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
    networks:
      - php-api-network
